# Generated by Django 2.2.5 on 2022-08-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='holiday_seasonal',
        ),
        migrations.AddField(
            model_name='recipe',
            name='holiday_seasonal',
            field=models.ManyToManyField(related_name='holyday_seasonal', to='main.HolidaysSeasonal'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='occasion',
        ),
        migrations.AddField(
            model_name='recipe',
            name='occasion',
            field=models.ManyToManyField(related_name='occasion', to='main.Occasion'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.ManyToManyField(related_name='type', to='main.Type'),
        ),
    ]
