# Generated by Django 2.2.5 on 2022-08-28 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220828_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidaysseasonal',
            old_name='period',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='holidaysseasonal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
