# Generated by Django 2.2.5 on 2022-08-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220828_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cusine',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Cusine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='holiday_seasonal',
            field=models.ManyToManyField(blank=True, related_name='holyday_seasonal', to='main.HolidaysSeasonal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Meal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='occasion',
            field=models.ManyToManyField(blank=True, related_name='occasion', to='main.Occasion'),
        ),
    ]
