# Generated by Django 2.2.5 on 2022-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220829_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='prep_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
    ]
