# Generated by Django 2.2.5 on 2022-08-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220829_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='cusine',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='holidaysseasonal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='level',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='occasion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='type',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='course',
        ),
        migrations.AddField(
            model_name='recipe',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='course', to='main.Course'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='cusine',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cusine',
            field=models.ManyToManyField(blank=True, related_name='cusine', to='main.Cusine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='holiday_seasonal',
            field=models.ManyToManyField(blank=True, related_name='holidays', to='main.HolidaysSeasonal'),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='meal', to='main.Meal'),
        ),
    ]
