# Generated by Django 2.2.5 on 2022-08-30 11:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220829_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main.Course'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cusine',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main.Cusine'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='holiday_seasonal',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main.HolidaysSeasonal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main.Meal'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='occasion',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main.Occasion'),
        ),
    ]
