# Generated by Django 2.2.5 on 2022-09-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusine',
            new_name='Cuisine',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_cuisine',
            field=models.ManyToManyField(related_name='interested_cuisine', to='main.Cuisine'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interested_type',
            field=models.ManyToManyField(related_name='interested_type', to='main.Type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.ManyToManyField(related_name='user_level', to='main.Level'),
        ),
    ]
