# Generated by Django 2.2.5 on 2022-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220903_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='image',
            new_name='cover_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.URLField(null=True),
        ),
    ]
